---


- name: Add Docker GPG apt Key install docker-ce & docker-compose
  block:
    - name: Add Docker Repository
      apt_repository:
        repo: "{{ item.docker_repo }}"
        state: "{{ item.docker_state }}"
        update_cache: yes
      loop: "{{ docker_vars }}"
      tags:
        - docker

    - name: install docker & docker-compose
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop: "{{ docker_packages }}"
      ignore_errors: True
      tags:
        - docker

    - name: download docker-compose
      shell: curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)"\
             -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose