---

- name: make directory for gitlab
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ gitlab_directory_list }}"
  tags:
    - docker

- name: install dependencies gpg key
  block:
    - name: Install gpg key
      apt-key:
        url: "{{ item.docker_gpg_key }}"
        state: "{{ item.docker_gpg_state }}"
      loop: "{{ docker_vars }}"
      tags:
        - docker

    - name: Install dependencies
      import_role:
        name: os/package
      vars:
        package_action: "install"
        package_list: "{{ dependencies }}"
      tags:
        - docker



