---

- name: make directory for gitlab
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ gitlab_directory_list }}"


- name: install dependencies & aptitude
  block:
    - name: Install aptitude
#      remote_user: "{{ deploy_user }}"
      apt:
        name: aptitude
        state: latest
        update_cache: yes

    - name: Install dependencies
#      remote_user: "{{ deploy_user }}"
      import_role:
        name: os/package
      vars:
        package_action: "install"
        package_list: "{{ dependencies }}"



