---

# install mysql
- name: install mysql
  yum:
    name: mysql
    state: present
    update_cache: yes
  become: yes

#start mysql
- name: Start msql
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes