---

- name: install software-properties-common
  apt:
    name: software-properties-common
    state: present
    update_cache: yes

- name: add a PPA repository
  apt_repository:
    validate_certs: no
    repo: 'ppa:ondrej/php'
    state: present

- name: add path on .bashrc
  shell:
    cmd: echo 'export PATH="${HOME}/.local/bin:$PATH"' >> ~/.bashrc

- name: install {{ python_packages }}
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ python_packages }}"

- name: Run a pipenv install
  environment:
    LANG: "en_GB.UTF-8"
  command: "pipenv --bare install --dev"
  args:
    chdir: "{{ project_root }}"
