---

- name: add .bashrc variables
  shell: "export APTOS_DIR={{ item.aptos_dir }} &&\
         export APTOS_VERSION={{ item.version }} &&\
         export APTOS_NAME={{ item.user }} &&\
         echo export APTOS_DIR=$APTOS_DIR >> $HOME/.bashrc &&\
         echo export APTOS_DIR=$APTOS_DIR >> $HOME/.profile &&\
         echo export APTOS_VERSION=$APTOS_VERSION >> $HOME/.bashrc &&\
         echo export APTOS_VERSION=$APTOS_VERSION >> $HOME/.profile &&\
         echo export APTOS_NAME=$APTOS_NAME >> $HOME/.bashrc &&\
         echo export APTOS_NAME=$APTOS_NAME >> $HOME/.profile"
  loop: "{{ aptos_project_vars }}"

- name: generate key
  shell: cd $APTOS_DIR && \
         aptos genesis generate-keys --output-dir $APTOS_DIR