---
- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ dependencies }}"

- name: Add Docker GPG apt Key install docker-ce & docker-compose
  block:
    - name: Add Docker GPG apt Key
      apt_key:
        url: "{{ item.docker_apt_key }}"
        state: "{{ item.docker_state }}"
      loop: "{{ docker_vars }}"

    - name: Add Docker Repository
      apt_repository:
        repo: "{{ item.docker_repo }}"
        state: "{{ item.docker_state }}"
      loop: "{{ docker_vars }}"

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: "{{ item.docker_state }}"
        update_cache: true
      loop: "{{ docker_vars }}"

    - name: Install Docker Module for Python
      pip:
        name: docker


- name: install docker & docker-compose
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ docker_packages }}"