---

- name: make aptos directory
  file:
    path: "{{ item.aptos_dir }}"
    state: directory
  loop: "{{ project_vars }}"

- name: download aptos-cli
  get_url: https://github.com/aptos-labs/aptos-core/releases/download/\
           aptos-cli-v{{project_vars.version}}/aptos-cli-$APTOS_VERSION-Ubuntu-x86_64.zip