---

- name: 'PREREQUISITES | prepare to install'
  import_tasks: prereq.yml

- name: 'INSTALL | install docker and dependencies'
  import_tasks: install.yml

- name: 'INSTALL_APTOS | install aptos '
  import_tasks: install_aptos_cli.yml



