---

- name: create directory
  file:
    path:
     - "{{ item.dir }}"
     - "{{ item.aptos_dir }}"
    state: directory
  loop: "{{ project_vars }}"

- name: copying script in workdir
  copy:
    src: script.sh
    dest: "{{ item.dir }}"
  loop: "{{ project_vars }}"