---


- name: create directory
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ directory }}"



#- name: copying script in workdir
#  copy:
#    src: script.sh
#    dest: "{{ item.dir }}"
#  loop: "{{ project_vars }}"

