---

# install vsftpd
- name: install vsftpd
  yum:
    name: vsftpd
    state: present
    update_cache: yes
  become: yes

- name: Start vsftpd
  service:
    name: vsftpd
    state: started
    enabled: yes
  become: yes