---

- name: copy docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: /root/docker-compose.yml
    tags:
      - docker

- name: custom port SSH
  shell: sed -i 's/Port 22/Port 2222/g' /etc/ssh/sshd_config
  notify:
    - restart_ssh_service
  tags:
    - docker

